name: CI
run-name: ${{ github.actor }} ci
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - silkeh/clang:20


    container:
      image: ${{matrix.image}}
      options: --user root

    steps:
      - name: install dependencies
        run: |
          apt update && \
          apt install -y \
            cmake \
            doctest-dev \
            libsqlite3-dev \
            ninja-build \
            uuid \
            uuid-dev

      - uses: actions/checkout@v4
      - name: install doctest
        run: apt update && apt install doctest

      - name: build
        run: make debug

      - name: test
        run: ./build-debug/bin/test
